import { OpeningDefinition } from './types';

export const OPENINGS_DB: Record<string, OpeningDefinition> = {
  // e4 openings
  "e4": { eco: "B00", name: "King's Pawn Game" },
  "e4 e5": { eco: "C20", name: "Open Game" },
  "e4 e5 Nf3": { eco: "C40", name: "King's Knight Opening" },
  "e4 e5 Nf3 Nc6": { eco: "C44", name: "Open Game: King's Pawn" },
  "e4 e5 Nf3 Nc6 Bc4": { eco: "C50", name: "Italian Game" },
  "e4 e5 Nf3 Nc6 Bc4 Bc5": { eco: "C50", name: "Italian Game", variation: "Giuoco Piano" },
  "e4 e5 Nf3 Nc6 Bc4 Nf6": { eco: "C55", name: "Italian Game", variation: "Two Knights Defense" },
  "e4 e5 Nf3 Nc6 Bb5": { eco: "C60", name: "Ruy Lopez" },
  "e4 e5 Nf3 Nc6 Bb5 a6": { eco: "C70", name: "Ruy Lopez", variation: "Morphy Defense" },
  "e4 e5 Nf3 Nc6 d4": { eco: "C44", name: "Scotch Game" },
  "e4 e5 Nf3 Nc6 d4 exd4": { eco: "C45", name: "Scotch Game", variation: "Main Line" },
  "e4 e5 f4": { eco: "C30", name: "King's Gambit" },
  "e4 e5 f4 exf4": { eco: "C33", name: "King's Gambit Accepted" },
  "e4 c5": { eco: "B20", name: "Sicilian Defense" },
  "e4 c5 Nf3": { eco: "B27", name: "Sicilian Defense", variation: "Open Sicilian" },
  "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3": { eco: "B90", name: "Sicilian Defense", variation: "Najdorf" },
  "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4": { eco: "B32", name: "Sicilian Defense", variation: "Old Sicilian" },
  "e4 e6": { eco: "C00", name: "French Defense" },
  "e4 e6 d4 d5": { eco: "C02", name: "French Defense", variation: "Normal Variation" },
  "e4 c6": { eco: "B10", name: "Caro-Kann Defense" },
  "e4 c6 d4 d5": { eco: "B12", name: "Caro-Kann Defense", variation: "Classical" },
  "e4 d6": { eco: "B07", name: "Pirc Defense" },
  "e4 Nf6": { eco: "B02", name: "Alekhine's Defense" },
  "e4 g6": { eco: "B06", name: "Modern Defense" },
  
  // d4 openings
  "d4": { eco: "A40", name: "Queen's Pawn Game" },
  "d4 d5": { eco: "D00", name: "Queen's Pawn Game: Closed" },
  "d4 d5 c4": { eco: "D06", name: "Queen's Gambit" },
  "d4 d5 c4 e6": { eco: "D30", name: "Queen's Gambit Declined" },
  "d4 d5 c4 c6": { eco: "D10", name: "Slav Defense" },
  "d4 d5 c4 dxc4": { eco: "D20", name: "Queen's Gambit Accepted" },
  "d4 Nf6": { eco: "A45", name: "Queen's Pawn Game: Indian Defense" },
  "d4 Nf6 c4 e6 Nf3 b6": { eco: "E12", name: "Queen's Indian Defense" },
  "d4 Nf6 c4 e6 Nc3 Bb4": { eco: "E20", name: "Nimzo-Indian Defense" },
  "d4 Nf6 c4 g6": { eco: "E60", name: "King's Indian Defense" },
  "d4 Nf6 c4 g6 Nc3 d5": { eco: "D80", name: "Gruenfeld Defense" },
  "d4 f5": { eco: "A80", name: "Dutch Defense" },

  // Flank openings
  "Nf3": { eco: "A04", name: "Reti Opening" },
  "Nf3 d5": { eco: "A09", name: "Reti Opening", variation: "Reti Accepted" },
  "c4": { eco: "A10", name: "English Opening" },
  "c4 e5": { eco: "A20", name: "English Opening", variation: "King's English" },
  "g3": { eco: "A00", name: "Benko's Opening" },
  "f4": { eco: "A02", name: "Bird's Opening" },
};
